POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Decoração",
    "description": "Escolha a decoração para sua festa, e nós a montamos.",
    "price": 1400,
    "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
}

###

GET http://localhost:3000/api/services

###

GET http://localhost:3000/api/services/6990f54a395b658b90fd8361

###

DELETE http://localhost:3000/api/services/698f88161257c4bad1c65e84

###

PUT http://localhost:3000/api/services/6990f5a6395b658b90fd8368
Content-Type: application/json

{
    "name": "Barman",
    "description": "Equipe com barman para servir drinks criativos aos convidados.",
    "price": 1400,
    "image": "https://images.unsplash.com/photo-1616781434243-b972f0c687b1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
}

###

POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Minha festa",
    "author": "Rafael",
    "description": "Festa",
    "budget": 10000,
    "image": "https://images.unsplash.com/photo-1770009079291-82b8a594ee23?q=80&w=409&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "services": [
        {
            "name": "serviço 3",
            "description": "descrição",
            "price": 3000,
            "image": "https://images.unsplash.com/photo-1770009079291-82b8a594ee23?q=80&w=409&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        },
        {
            "name": "serviço 4",
            "description": "descrição",
            "price": 2000,
            "image": "https://images.unsplash.com/photo-1770009079291-82b8a594ee23?q=80&w=409&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        }
    ]
}

###

GET http://localhost:3000/api/parties

###

GET http://localhost:3000/api/parties/699086b923d45fa9f23cf6eb

###

DELETE http://localhost:3000/api/parties/699087ad23d45fa9f23cf6ed

###

PUT http://localhost:3000/api/parties/699086b923d45fa9f23cf6eb
Content-Type: application/json

{
    "title": "Minha festa",
    "author": "Rafael",
    "description": "Festa",
    "budget": 10000,
    "image": "https://images.unsplash.com/photo-1770009079291-82b8a594ee23?q=80&w=409&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "services": [
        {
            "name": "serviço 3",
            "description": "descrição",
            "price": 3000,
            "image": "https://images.unsplash.com/photo-1770009079291-82b8a594ee23?q=80&w=409&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        },
        {
            "name": "serviço 4",
            "description": "descrição",
            "price": 2000,
            "image": "https://images.unsplash.com/photo-1770009079291-82b8a594ee23?q=80&w=409&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        }
    ]
}
