POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Algum serviço 2",
    "description": "descrição",
    "price": 2000,
    "image": "https://images.unsplash.com/photo-1770009079291-82b8a594ee23?q=80&w=409&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}

###

GET http://localhost:3000/api/services

###

GET http://localhost:3000/api/services/698f8cacf639885692068a74

###

DELETE http://localhost:3000/api/services/698f88161257c4bad1c65e84

###

PUT http://localhost:3000/api/services/698f8cacf639885692068a74
Content-Type: application/json

{
    "name": "Algum serviço",
    "description": "descrição",
    "price": 2000,
    "image": "https://images.unsplash.com/photo-1770009079291-82b8a594ee23?q=80&w=409&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}

###

POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Minha festa",
    "author": "Rafael",
    "description": "Festa",
    "budget": 10000,
    "image": "https://images.unsplash.com/photo-1770009079291-82b8a594ee23?q=80&w=409&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "services": [
        {
            "name": "serviço 3",
            "description": "descrição",
            "price": 3000,
            "image": "https://images.unsplash.com/photo-1770009079291-82b8a594ee23?q=80&w=409&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        },
        {
            "name": "serviço 4",
            "description": "descrição",
            "price": 2000,
            "image": "https://images.unsplash.com/photo-1770009079291-82b8a594ee23?q=80&w=409&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        }
    ]
}